insert into team (name) values ('Fria');
insert into team (name) values ('Hlyboka');
insert into team (name) values ('Odolanów');
insert into team (name) values ('Jefferson City');
insert into team (name) values ('Волочаевское');
insert into team (name) values ('Grazhdanskoye');
insert into team (name) values ('Nýřany');
insert into team (name) values ('Minggang');
insert into team (name) values ('Saint-Flour');
insert into team (name) values ('Cheongpyeong');
insert into team (name) values ('Isiro');
insert into team (name) values ('Kutasari');
insert into team (name) values ('Zengtian');
insert into team (name) values ('Jinji');
insert into team (name) values ('Xiyuan');
insert into team (name) values ('Los Tangos');
insert into team (name) values ('Maungatapere');
insert into team (name) values ('Shihuajian');
insert into team (name) values ('Mölndal');
insert into team (name) values ('Dębno');

insert into game (id_team_a, id_team_b, datetime, stadium) values (18, 18, '2022-06-01 18:09:24', 'Duba-Yurt');
insert into game (id_team_a, id_team_b, datetime, stadium) values (6, 17, '2022-02-05 11:33:20', 'Maipú');
insert into game (id_team_a, id_team_b, datetime, stadium) values (7, 19, '2022-06-26 21:48:31', 'Bondokodi');
insert into game (id_team_a, id_team_b, datetime, stadium) values (9, 10, '2022-04-02 02:27:02', 'Arenal');
insert into game (id_team_a, id_team_b, datetime, stadium) values (17, 16, '2022-03-03 14:47:12', 'Guaíba');
insert into game (id_team_a, id_team_b, datetime, stadium) values (16, 18, '2022-02-22 01:35:16', 'Veselí nad Lužnicí');
insert into game (id_team_a, id_team_b, datetime, stadium) values (14, 9, '2022-05-05 01:53:58', 'Cibolang');
insert into game (id_team_a, id_team_b, datetime, stadium) values (16, 14, '2022-05-02 18:16:13', 'Solotcha');
insert into game (id_team_a, id_team_b, datetime, stadium) values (8, 14, '2022-02-05 02:27:52', 'Solnechnogorsk');
insert into game (id_team_a, id_team_b, datetime, stadium) values (13, 16, '2022-10-08 11:17:24', 'Zhagang');
insert into game (id_team_a, id_team_b, datetime, stadium) values (10, 3, '2022-12-08 03:46:07', 'Salyan');
insert into game (id_team_a, id_team_b, datetime, stadium) values (14, 20, '2022-03-27 09:22:42', 'Xihu');
insert into game (id_team_a, id_team_b, datetime, stadium) values (7, 14, '2022-11-21 17:37:55', 'Shitouhe');
insert into game (id_team_a, id_team_b, datetime, stadium) values (9, 4, '2022-12-07 02:43:18', 'San Vicente de Moravia');
insert into game (id_team_a, id_team_b, datetime, stadium) values (11, 5, '2022-03-08 14:14:42', 'Szczawnica');
insert into game (id_team_a, id_team_b, datetime, stadium) values (9, 14, '2022-08-02 18:47:33', 'Kungshamn');
insert into game (id_team_a, id_team_b, datetime, stadium) values (10, 6, '2022-09-28 17:00:11', 'Arlington');
insert into game (id_team_a, id_team_b, datetime, stadium) values (18, 6, '2022-05-29 08:45:21', 'Damayan');
insert into game (id_team_a, id_team_b, datetime, stadium) values (14, 10, '2022-05-21 05:27:07', 'Toktogul');
insert into game (id_team_a, id_team_b, datetime, stadium) values (12, 20, '2021-12-18 21:51:55', 'Gaplek');
insert into game (id_team_a, id_team_b, datetime, stadium) values (13, 15, '2022-05-01 11:47:56', 'Hongyansi');
insert into game (id_team_a, id_team_b, datetime, stadium) values (3, 18, '2022-10-19 18:54:32', 'Lankaran');
insert into game (id_team_a, id_team_b, datetime, stadium) values (12, 12, '2022-06-24 14:47:49', 'Būsh');
insert into game (id_team_a, id_team_b, datetime, stadium) values (4, 11, '2022-09-15 01:07:52', 'Xylókastro');
insert into game (id_team_a, id_team_b, datetime, stadium) values (18, 18, '2022-12-16 19:51:12', 'Ágios Geórgios');
insert into game (id_team_a, id_team_b, datetime, stadium) values (1, 7, '2022-10-27 18:46:06', 'Moravský Beroun');
insert into game (id_team_a, id_team_b, datetime, stadium) values (14, 5, '2022-04-09 02:03:37', 'Haikoudajie');
insert into game (id_team_a, id_team_b, datetime, stadium) values (17, 17, '2022-07-18 16:44:45', 'Magumeri');
insert into game (id_team_a, id_team_b, datetime, stadium) values (20, 15, '2022-02-19 16:36:57', 'Lũng Hồ');
insert into game (id_team_a, id_team_b, datetime, stadium) values (2, 16, '2022-01-06 17:14:16', 'Cereté');

insert into player (name, number, id_team) values ('Myra Vittori', 61, 1);
insert into player (name, number, id_team) values ('Deeyn Cecchi', 13, 6);
insert into player (name, number, id_team) values ('Way Winspire', 10, 5);
insert into player (name, number, id_team) values ('Donovan Trittam', 28, 18);
insert into player (name, number, id_team) values ('Horacio Faulder', 55, 20);
insert into player (name, number, id_team) values ('Davida Ostler', 49, 6);
insert into player (name, number, id_team) values ('Lois Hudless', 48, 19);
insert into player (name, number, id_team) values ('Pegeen Harrod', 93, 5);
insert into player (name, number, id_team) values ('Pamela Vispo', 46, 12);
insert into player (name, number, id_team) values ('Evelyn Budnk', 86, 1);
insert into player (name, number, id_team) values ('Eula O''Hear', 44, 18);
insert into player (name, number, id_team) values ('Fitz Beswick', 14, 1);
insert into player (name, number, id_team) values ('Alvan Callum', 27, 16);
insert into player (name, number, id_team) values ('Wenda Feronet', 26, 12);
insert into player (name, number, id_team) values ('Colman Jeratt', 47, 5);
insert into player (name, number, id_team) values ('Cynthia Radolf', 44, 10);
insert into player (name, number, id_team) values ('Jasmine Demke', 93, 18);
insert into player (name, number, id_team) values ('Bidget Coghill', 40, 6);
insert into player (name, number, id_team) values ('Zane Orrocks', 4, 15);
insert into player (name, number, id_team) values ('Mona Binnes', 21, 5);
insert into player (name, number, id_team) values ('Bay Fehely', 12, 11);
insert into player (name, number, id_team) values ('Amory Coggan', 90, 18);
insert into player (name, number, id_team) values ('Kippy Ghiriardelli', 33, 13);
insert into player (name, number, id_team) values ('Son Moehler', 86, 2);
insert into player (name, number, id_team) values ('Noam Reddecliffe', 48, 2);
insert into player (name, number, id_team) values ('Dion Marjot', 86, 6);
insert into player (name, number, id_team) values ('Fidelio Errington', 38, 14);
insert into player (name, number, id_team) values ('Eolande Coundley', 66, 12);
insert into player (name, number, id_team) values ('Juliane Pingston', 90, 13);
insert into player (name, number, id_team) values ('Susannah Stobart', 12, 3);
insert into player (name, number, id_team) values ('Eldridge Blamey', 86, 12);
insert into player (name, number, id_team) values ('Darda Duplock', 80, 1);
insert into player (name, number, id_team) values ('Alex McCaffrey', 82, 8);
insert into player (name, number, id_team) values ('Cy Gillbanks', 31, 9);
insert into player (name, number, id_team) values ('Austen Filewood', 96, 3);
insert into player (name, number, id_team) values ('Aurea Nares', 22, 13);
insert into player (name, number, id_team) values ('Wain Eastmead', 45, 9);
insert into player (name, number, id_team) values ('Clemente Mellsop', 21, 8);
insert into player (name, number, id_team) values ('Dalli Bradburn', 8, 11);
insert into player (name, number, id_team) values ('Logan Sonier', 68, 16);
insert into player (name, number, id_team) values ('Barry Shorie', 96, 6);
insert into player (name, number, id_team) values ('Georgette Thurlbourne', 39, 5);
insert into player (name, number, id_team) values ('Durant Braban', 15, 6);
insert into player (name, number, id_team) values ('Brooks Laise', 70, 18);
insert into player (name, number, id_team) values ('Clare Wickerson', 84, 17);
insert into player (name, number, id_team) values ('Cristian Laker', 76, 19);
insert into player (name, number, id_team) values ('Neysa Willard', 7, 11);
insert into player (name, number, id_team) values ('Nicoli Inskipp', 98, 8);
insert into player (name, number, id_team) values ('Celina Gandrich', 81, 2);
insert into player (name, number, id_team) values ('Elston Jennemann', 10, 5);
insert into player (name, number, id_team) values ('Vittorio Lorkings', 66, 17);
insert into player (name, number, id_team) values ('Jennee Dummer', 2, 18);
insert into player (name, number, id_team) values ('Adriano Dackombe', 42, 4);
insert into player (name, number, id_team) values ('Aubrette Larwell', 23, 20);
insert into player (name, number, id_team) values ('Denice Huortic', 81, 6);
insert into player (name, number, id_team) values ('Leonid Munning', 34, 5);
insert into player (name, number, id_team) values ('Babita Mowle', 91, 12);
insert into player (name, number, id_team) values ('Raquel Jardein', 47, 14);
insert into player (name, number, id_team) values ('Devinne Dallinder', 66, 3);
insert into player (name, number, id_team) values ('Tiffanie Wreakes', 76, 1);
insert into player (name, number, id_team) values ('Merci Stoner', 7, 12);
insert into player (name, number, id_team) values ('Oren Petras', 22, 12);
insert into player (name, number, id_team) values ('Ansell Phifer', 48, 19);
insert into player (name, number, id_team) values ('Angela Terbruggen', 36, 10);
insert into player (name, number, id_team) values ('Marin Sentinella', 34, 11);
insert into player (name, number, id_team) values ('Mab Birdwhistell', 8, 20);
insert into player (name, number, id_team) values ('Brandice Crone', 17, 5);
insert into player (name, number, id_team) values ('Clio Gallardo', 83, 8);
insert into player (name, number, id_team) values ('Tybie Bage', 42, 18);
insert into player (name, number, id_team) values ('Dinny Cicchillo', 56, 12);
insert into player (name, number, id_team) values ('Yevette Carnilian', 72, 20);
insert into player (name, number, id_team) values ('Andromache Tuite', 40, 2);
insert into player (name, number, id_team) values ('Berkly Rankmore', 2, 12);
insert into player (name, number, id_team) values ('Darnall Battram', 59, 10);
insert into player (name, number, id_team) values ('Horten Moloney', 87, 4);
insert into player (name, number, id_team) values ('Hannie Jarman', 21, 3);
insert into player (name, number, id_team) values ('Grier Cathersides', 16, 14);
insert into player (name, number, id_team) values ('Charmaine Pauler', 61, 20);
insert into player (name, number, id_team) values ('Alyssa Martinetto', 79, 19);
insert into player (name, number, id_team) values ('Rennie Desorts', 59, 19);
insert into player (name, number, id_team) values ('Ingrid Marages', 1, 16);
insert into player (name, number, id_team) values ('Emma Rodgers', 52, 17);
insert into player (name, number, id_team) values ('Hilde Ulyatt', 56, 9);
insert into player (name, number, id_team) values ('Megen Beevis', 91, 11);
insert into player (name, number, id_team) values ('Berti Strafen', 42, 6);
insert into player (name, number, id_team) values ('Bert Giaomozzo', 9, 7);
insert into player (name, number, id_team) values ('Steffane MacKall', 77, 12);
insert into player (name, number, id_team) values ('Francene Campany', 41, 4);
insert into player (name, number, id_team) values ('Kelsi Durrant', 51, 20);
insert into player (name, number, id_team) values ('Alanah Darbishire', 37, 11);
insert into player (name, number, id_team) values ('Noah Gwyneth', 46, 2);
insert into player (name, number, id_team) values ('Carly Moverley', 51, 7);
insert into player (name, number, id_team) values ('Gardner Feldhuhn', 90, 7);
insert into player (name, number, id_team) values ('Loree McGillreich', 17, 9);
insert into player (name, number, id_team) values ('Joy Boeter', 90, 8);
insert into player (name, number, id_team) values ('Brennen Villalta', 7, 2);
insert into player (name, number, id_team) values ('Sile Zini', 17, 5);
insert into player (name, number, id_team) values ('Denna Adamek', 12, 18);
insert into player (name, number, id_team) values ('Brynne Stone Fewings', 96, 18);
insert into player (name, number, id_team) values ('Allyn Delgadillo', 62, 7);

insert into sponsors (name) values ('Pixoboo');
insert into sponsors (name) values ('Wordify');
insert into sponsors (name) values ('Realcube');
insert into sponsors (name) values ('Zoomlounge');
insert into sponsors (name) values ('Tazzy');
insert into sponsors (name) values ('Devpoint');
insert into sponsors (name) values ('Twimbo');
insert into sponsors (name) values ('Dabtype');
insert into sponsors (name) values ('Bluejam');
insert into sponsors (name) values ('Jetpulse');
insert into sponsors (name) values ('Demimbu');
insert into sponsors (name) values ('Thoughtstorm');
insert into sponsors (name) values ('Muxo');
insert into sponsors (name) values ('Livetube');
insert into sponsors (name) values ('Youtags');
insert into sponsors (name) values ('Youspan');
insert into sponsors (name) values ('Livetube');
insert into sponsors (name) values ('Pixope');
insert into sponsors (name) values ('Jaxnation');
insert into sponsors (name) values ('Jabbertype');
insert into sponsors (name) values ('Skidoo');
insert into sponsors (name) values ('Bubblemix');
insert into sponsors (name) values ('Rhynyx');
insert into sponsors (name) values ('Meedoo');
insert into sponsors (name) values ('Gigaclub');
insert into sponsors (name) values ('Jayo');
insert into sponsors (name) values ('Shufflebeat');
insert into sponsors (name) values ('Yadel');
insert into sponsors (name) values ('Topiclounge');
insert into sponsors (name) values ('Browsezoom');


insert into have (id_sponsor, id_team) values (18, 11);
insert into have (id_sponsor, id_team) values (15, 16);
insert into have (id_sponsor, id_team) values (5, 10);
insert into have (id_sponsor, id_team) values (12, 3);
insert into have (id_sponsor, id_team) values (16, 11);
insert into have (id_sponsor, id_team) values (20, 2);
insert into have (id_sponsor, id_team) values (8, 9);
insert into have (id_sponsor, id_team) values (2, 16);
insert into have (id_sponsor, id_team) values (28, 8);
insert into have (id_sponsor, id_team) values (5, 20);
insert into have (id_sponsor, id_team) values (18, 14);
insert into have (id_sponsor, id_team) values (26, 14);
insert into have (id_sponsor, id_team) values (13, 8);
insert into have (id_sponsor, id_team) values (29, 13);
insert into have (id_sponsor, id_team) values (23, 17);
insert into have (id_sponsor, id_team) values (29, 4);
insert into have (id_sponsor, id_team) values (26, 18);
insert into have (id_sponsor, id_team) values (21, 20);
insert into have (id_sponsor, id_team) values (1, 19);
insert into have (id_sponsor, id_team) values (3, 12);
insert into have (id_sponsor, id_team) values (19, 18);
insert into have (id_sponsor, id_team) values (4, 17);
insert into have (id_sponsor, id_team) values (30, 4);
insert into have (id_sponsor, id_team) values (19, 6);
insert into have (id_sponsor, id_team) values (27, 16);
insert into have (id_sponsor, id_team) values (29, 19);
insert into have (id_sponsor, id_team) values (7, 3);
insert into have (id_sponsor, id_team) values (14, 20);
insert into have (id_sponsor, id_team) values (16, 11);
insert into have (id_sponsor, id_team) values (9, 20);
insert into have (id_sponsor, id_team) values (14, 11);
insert into have (id_sponsor, id_team) values (3, 18);
insert into have (id_sponsor, id_team) values (30, 3);
insert into have (id_sponsor, id_team) values (18, 13);
insert into have (id_sponsor, id_team) values (5, 20);
insert into have (id_sponsor, id_team) values (9, 12);
insert into have (id_sponsor, id_team) values (28, 20);
insert into have (id_sponsor, id_team) values (15, 19);
insert into have (id_sponsor, id_team) values (15, 15);
insert into have (id_sponsor, id_team) values (30, 16);